/**
 * Diagram command system.
 *
 * Commands are plain JSON objects that describe a mutation to the diagram.
 * The LLM produces an array of these; the executor applies them to the
 * in-memory capability tree and/or the canvas node-style map.
 */

export type DiagramCommand =
  /** Change background fill and/or border colour of a node */
  | {
      type: "SET_STYLE";
      /** Capability ID (uuid) */
      nodeId: string;
      fill?: string;   // CSS hex e.g. "#ff0000"
      border?: string; // CSS hex e.g. "#333333"
    }
  /** Attach or replace a text note on a node */
  | {
      type: "SET_NOTE";
      nodeId: string;
      note: string;
    }
  /** Rename a capability */
  | {
      type: "RENAME_NODE";
      nodeId: string;
      newName: string;
    }
  /** Move a node to a different parent (must obey level hierarchy) */
  | {
      type: "REPARENT_NODE";
      nodeId: string;
      /** ID of the new parent capability */
      newParentId: string;
    }
  /**
   * Permanently delete a node and all its descendants.
   * Use with caution — irreversible without an undo stack.
   */
  | {
      type: "DELETE_NODE";
      nodeId: string;
      /**
       * When true, children of the deleted node are re-parented to its parent
       * instead of being deleted with it. Defaults to false (cascade delete).
       */
      reparentChildren?: boolean;
    }
  /** Add a new capability node to the diagram */
  | {
      type: "ADD_NODE";
      /** UUID to assign — generated by the LLM as a valid v4 UUID string */
      tempId: string;
      /** ID of the parent capability. null only for L0 nodes. */
      parentId: string | null;
      level: 0 | 1 | 2 | 3;
      name: string;
      description?: string;
      /** Insert after this sibling's sort_order. null/omitted = append to end. */
      insertAfterId?: string | null;
    }
  /** Update the description field of an existing node */
  | {
      type: "SET_DESCRIPTION";
      nodeId: string;
      description: string;
    };

/** Keyed by nodeId; merged into ReactFlow node.data on the canvas */
export type NodeStylePatch = {
  fill?: string;
  border?: string;
  note?: string;
  description?: string;
};

export interface ChatHistoryMessage {
  role: "user" | "assistant";
  content: string;
}

export interface TransformRequest {
  prompt: string;
  capabilities: import("@/types/capability").Capability[];
  /** Current per-node visual overrides already on the canvas */
  nodeStyles?: Record<string, NodeStylePatch>;
  /** Prior conversation turns to give the LLM context across messages */
  history?: ChatHistoryMessage[];
  /**
   * "command" (default) — AI applies changes directly.
   * "suggest" — AI returns proposals the user can accept or decline.
   * "chat" — AI answers in plain text (listing, counting, describing nodes).
   */
  mode?: "command" | "suggest" | "chat";
}

export interface TransformResponse {
  commands: DiagramCommand[];
  /** Human-readable summary from the LLM */
  summary: string;
}

/** A single AI suggestion the user can accept or decline */
export type Proposal = {
  /** Stable ID generated by the AI (e.g. "p1", "p2") */
  id: string;
  /** Human-readable explanation of what will change and why */
  description: string;
  /** The command to execute if the user accepts this proposal */
  command: DiagramCommand;
};

export interface SuggestResponse {
  proposals: Proposal[];
  summary: string;
}
